In [2]:
from scipy.stats import norm, t
import numpy as np

---
__1__ Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):  

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],  

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].  

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy  
Полученные значения должны быть равны.  
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

---


In [63]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
zp, ks

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [52]:
mu_zp_ks = np.sum(zp*ks) / len(zp*ks)
mu_zp = np.sum(zp) / len(zp)
mu_ks = np.sum(ks) /len(ks)
mu_zp_ks, mu_zp, mu_ks

(81141.7, 101.4, 709.9)

In [53]:
cov_zp_ks = mu_zp_ks - mu_zp * mu_ks
cov_zp_ks

# cov_zp_ks = np.mean(zp_ks) - np.mean(zp) * np.mean(ks)

9157.839999999997

In [48]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [64]:
sigma_zp = np.sqrt(np.sum((zp - mu_zp)**2) / (len(zp) - 1))
sigma_ks = np.sqrt(np.sum((ks - mu_ks)**2) / (len(ks) - 1))
sigma_zp, sigma_ks  

(62.31318747531162, 183.99544076477068)

In [72]:
#  корреляция для несмещенных отклонений

corr_zp_ks = np.cov(zp, ks, ddof=1) / (sigma_zp * sigma_ks)
corr_zp_ks[1, 0]

0.887490092073916

In [73]:
#  корреляция для смещенных отклонений
corr_zp_ks = np.cov(zp, ks, ddof=0) / (np.std(zp) * np.std(ks))
corr_zp_ks[1, 0]

0.8874900920739162

In [71]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

---
__2__ Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:  

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.  

Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.  

---

Интервальная оценка:
$$\overline{X} \pm t_{\alpha /2} \cdot \frac{\sigma_{н}}{\sqrt{n}}$$  
$$\frac{\alpha}{2} = \frac{1 - 0.95}{2} = 0.025 \Rightarrow t_{\alpha /2} = 2.262$$

In [3]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [4]:
# mean_iq = np.mean(iq)
n = len(iq)
mean_iq = np.sum(iq) / n
mean_iq

118.1

In [5]:
# sigma_iq = np.std(iq, ddof=1)
sigma_iq = np.sqrt(np.sum((iq - mean_iq)**2) / (n - 1))
sigma_iq

10.54566788359614

In [7]:
t_table = abs(t.ppf(0.025, n - 1))
t_table

2.262157162740992

In [10]:
interval = [mean_iq + t_table* sigma_iq / np.sqrt(n) , mean_iq - t_table* sigma_iq / np.sqrt(n)]
interval

[125.64391634841274, 110.55608365158724]

---
__3__ Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

---

Интервальная оценка:
$$\overline{X} \pm Z_{\alpha /2} \cdot \frac{\sigma}{\sqrt{n}}$$  
$$\frac{\alpha}{2} = \frac{1 - 0.95}{2} = 0.025 \Rightarrow Z_{\alpha /2} = 1.96$$
$$174.2 \pm 1.96 \cdot \frac{\sqrt{25}}{\sqrt{27}}$$ 
$$\Bigr[174.2 - 1,886 ; 174.2 + 1,886] \Rightarrow [172.31; 176.08]$$

In [11]:
x_mean = 174.2
var = 25
sigma = np.sqrt(var)
n = 27
z_table = abs(norm.ppf(0.025))

interval = [x_mean - z_table* (sigma / np.sqrt(n)), x_mean + z_table* (sigma / np.sqrt(n))]
interval

[172.3140237765397, 176.08597622346028]