In [11]:
import numpy as np
from scipy import stats

---
__1__ Провести дисперсионный анализ для определения того, есть ли различия среднего роста среди взрослых футболистов, хоккеистов и штангистов. Даны значения роста в трех группах случайно выбранных спортсменов:   
Футболисты: 173, 175, 180, 178, 177, 185, 183, 182.   
Хоккеисты: 177, 179, 180, 188, 177, 172, 171, 184, 180.   
Штангисты: 172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170.

---


In [13]:
footbollers = np.array([173, 175, 180, 178, 177, 185, 183, 182])
hockey_players = np.array([177, 179, 180, 188, 177, 172, 171, 184, 180])
weightlifters = np.array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170])
footbollers, hockey_players, weightlifters

(array([173, 175, 180, 178, 177, 185, 183, 182]),
 array([177, 179, 180, 188, 177, 172, 171, 184, 180]),
 array([172, 173, 169, 177, 166, 180, 178, 177, 172, 166, 170]))

In [14]:
stats.f_oneway(footbollers, hockey_players, weightlifters)

F_onewayResult(statistic=5.500053450812596, pvalue=0.010482206918698694)

Так как pvalue < 0.05, то на уровне значимости $\alpha = 5\%$ есть статистически значимые различия роста. Если взять $\alpha = 1\%$ то статистически значимых различий нет.